# -*- coding: utf-8 -*-
"""球鏡展開校正工具(橋二;HANDOFF §9C 的軟體半邊)。

功能:
  1. 幾何前向模型:相機朝上拍球鏡,像素半徑 ρ ↔ 世界仰角 ε 的映射
     (球面鏡反射閉式解;非中心系統,同時回報等效視點高度與其散佈)。
  2. LUT 生成:極座標 → 64×48 等角全景的查表(輸出 .npy 與 C 標頭)。
  3. 合成驗證:把模擬世界光線追蹤成「假 OV2640 球照」→ 用 LUT 攤平 →
     與 PanoCamera 解析全景比對,RIDF 應 ≈0°;再轉 +30° 驗證手性/符號
     (= smoke_test 第 1 段的 LUT 版)。

實機用法(拿到硬體後):
  - 拍一張球照,量出球輪廓圓心 (CX,CY) 與輪廓半徑 rim_px;
  - 由機構圖取 BALL_R 與 BALL_D → u_max = asin(R/D),f = rim_px / tan(u_max);
  - 改填下方常數重跑本檔即得實機 LUT;左右手性若反(smoke §1 符號測試會抓到)
    把 AZ_SIGN 反號重生;
  - 棋盤/已知圓筒精修(非中心殘差、鏡面橢圓度)留待硬體到位。

注意:若實機幾何算出的仰角範圍與 config 的 EL_TOP/EL_BOT(55/−5°)不符,
必須回填 config 並重推 COMPASS_ROWS、重跑 smoke_test 門檻(config 內有警語)。
"""
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import config as C
from world import World, PanoCamera
from brain import norm, ridf, img_diff

# ---- 幾何常數(佔位:由機構圖/實照回填) ----
BALL_R     = 0.025      # 球半徑 m(50mm 空心不鏽鋼球)
BALL_D     = 0.115      # 相機光心 → 球心距離 m(桅高扣相機座)
CAM_BASE_H = 0.05       # 相機光心離地高 m
IMG_W = IMG_H = 240     # 感測器裁切
FOV_DEG    = 66.0       # 鏡頭全視角
AZ_SIGN    = +1.0       # 手性;實機若 RIDF 符號反了改 −1 重生 LUT

F_PX  = (IMG_W / 2) / np.tan(np.deg2rad(FOV_DEG / 2))
CX, CY = IMG_W / 2 - 0.5, IMG_H / 2 - 0.5
U_MAX = np.arcsin(BALL_R / BALL_D)


def reflect_table(n=4000):
    """回傳 (u, ε, P_z):相機視線角 u → 世界仰角 ε 與反射點高度(球下緣起算)。"""
    u = np.linspace(1e-5, U_MAX * (1 - 1e-6), n)
    d = np.stack([np.sin(u), np.cos(u)])                  # (x, z) 視線方向
    c = BALL_D * d[1]
    t = c - np.sqrt(np.maximum(c * c - (BALL_D**2 - BALL_R**2), 0.0))
    P = t * d                                             # 反射點
    nx, nz = (P[0] - 0.0) / BALL_R, (P[1] - BALL_D) / BALL_R
    dot = d[0] * nx + d[1] * nz
    rx, rz = d[0] - 2 * dot * nx, d[1] - 2 * dot * nz     # 反射方向(出射)
    eps = np.arctan2(rz, rx)                              # 仰角(rx>0 同側外射)
    return u, eps, P[1]


def build_lut(u_tab, eps_tab):
    """輸出 (lut_x, lut_y) float (48,64):全景像素 ← 球照像素座標。"""
    el_rows = np.linspace(C.EL_TOP, C.EL_BOT, C.PANO_H)
    order = np.argsort(eps_tab)
    u_rows = np.interp(el_rows, eps_tab[order], u_tab[order])
    rho = F_PX * np.tan(u_rows)                           # (48,)
    beta = np.arange(C.PANO_W) * 2 * np.pi / C.PANO_W     # col: 車頭起逆時針
    lut_x = CX + rho[:, None] * np.cos(AZ_SIGN * beta)[None, :]
    lut_y = CY - rho[:, None] * np.sin(AZ_SIGN * beta)[None, :]   # 影像 y 向下
    return lut_x, lut_y, rho, el_rows


def synth_ball_image(world, x, y, theta, u_tab, eps_tab, cam_h_eff):
    """光線追蹤:模擬世界 → 假 OV2640 球照(遠景近似:視點=車心 cam_h_eff)。"""
    px, py = np.meshgrid(np.arange(IMG_W, dtype=float), np.arange(IMG_H, dtype=float))
    dx, dy = px - CX, CY - py                             # y 翻回數學座標
    rho = np.hypot(dx, dy)
    mask = rho < F_PX * np.tan(U_MAX) * 0.999
    u = np.arctan(rho[mask] / F_PX)
    eps = np.interp(u, u_tab, eps_tab)
    alpha = theta + AZ_SIGN * np.arctan2(dy[mask], dx[mask])
    # 與 PanoCamera 相同的剪影著色,但逐像素任意 (α, ε)
    dw, sw = world.wall_hit(x, y, alpha)
    hw = world.skyline_at(sw)
    top = np.arctan2(hw - cam_h_eff, dw)
    bot = np.arctan2(-cam_h_eff, dw)
    dark = (eps <= top) & (eps >= bot)
    for (cx0, cy0, r, h) in world.cyl:
        ddx, ddy = cx0 - x, cy0 - y
        dc = np.hypot(ddx, ddy)
        if dc <= r + 1e-6:
            continue
        phi = np.arctan2(ddy, ddx)
        gam = np.arcsin(np.clip(r / dc, 0, 1))
        cov = np.abs((alpha - phi + np.pi) % (2 * np.pi) - np.pi) <= gam
        d = max(dc - r, 1e-3)
        dark |= cov & (eps <= np.arctan2(h - cam_h_eff, d)) & (eps >= np.arctan2(-cam_h_eff, d))
    val = np.full(eps.shape, 0.80)
    val[eps < 0] = 0.48
    val[dark] = 0.10
    img = np.zeros((IMG_H, IMG_W))
    img[mask] = val
    return img


def unwarp(ball_img, lut_x, lut_y):
    """最近鄰(= 韌體 C LUT 的行為)。"""
    ix = np.clip(np.rint(lut_x).astype(int), 0, IMG_W - 1)
    iy = np.clip(np.rint(lut_y).astype(int), 0, IMG_H - 1)
    return ball_img[iy, ix]


def unwarp_bilinear(ball_img, lut_x, lut_y):
    """雙線性(驗證採用;韌體 4 taps,ESP32 可負擔,建議採用——
    最近鄰在薄環帶會把 RIDF 次像素角度咬出 ~1.5° 偏差,見閉環驗證)。"""
    x0 = np.clip(np.floor(lut_x).astype(int), 0, IMG_W - 2)
    y0 = np.clip(np.floor(lut_y).astype(int), 0, IMG_H - 2)
    fx, fy = lut_x - x0, lut_y - y0
    return ((1-fx)*(1-fy)*ball_img[y0, x0] + fx*(1-fy)*ball_img[y0, x0+1]
            + (1-fx)*fy*ball_img[y0+1, x0] + fx*fy*ball_img[y0+1, x0+1])


def export_c(lut_x, lut_y, path='pano_lut.h'):
    xi = np.rint(lut_x).astype(np.uint16).ravel()
    yi = np.rint(lut_y).astype(np.uint16).ravel()
    inter = np.empty(xi.size * 2, np.uint16)
    inter[0::2], inter[1::2] = xi, yi
    body = ',\n'.join(', '.join(map(str, inter[i:i+16])) for i in range(0, inter.size, 16))
    with open(path, 'w') as f:
        f.write('// auto-generated by mirror_calib.py — polar->64x48 unwarp LUT\n'
                f'#define PANO_W {C.PANO_W}\n#define PANO_H {C.PANO_H}\n'
                f'#define LUT_IMG_W {IMG_W}\n#define LUT_IMG_H {IMG_H}\n'
                '// PANO_LUT[(row*PANO_W+col)*2 + {0:x,1:y}] = source pixel (nearest)\n'
                f'const unsigned short PANO_LUT[{inter.size}] = {{\n{body}\n}};\n')


if __name__ == '__main__':
    u_tab, eps_tab, pz_tab = reflect_table()

    print('=== 幾何可行性(把「假設」變「推導」) ===')
    print(f'u_max = {np.rad2deg(U_MAX):.2f}°  球輪廓半徑 = {F_PX*np.tan(U_MAX):.1f} px')
    print(f'仰角可達範圍: {np.rad2deg(eps_tab.min()):.1f}° … {np.rad2deg(eps_tab.max()):.1f}°'
          f'(config 假設 {np.rad2deg(C.EL_TOP):.0f}/{np.rad2deg(C.EL_BOT):.0f}°)')
    band = (eps_tab >= C.EL_BOT) & (eps_tab <= C.EL_TOP)
    cam_h_eff = CAM_BASE_H + float(np.median(pz_tab[band]))
    print(f'等效視點高度 = {cam_h_eff*100:.1f} cm(config CAM_H = {C.CAM_H*100:.0f} cm;'
          f'非中心散佈 ±{np.ptp(pz_tab[band])*50:.1f} mm)')
    lut_x, lut_y, rho_rows, el_rows = build_lut(u_tab, eps_tab)
    for e_deg in (55, 25, 0, -5):
        i = int(np.argmin(np.abs(np.rad2deg(el_rows) - e_deg)))
        drho = abs(rho_rows[min(i+1, C.PANO_H-1)] - rho_rows[max(i-1, 0)]) / 2
        print(f'  ε={e_deg:+3d}°: 環半徑 {rho_rows[i]:5.1f} px,徑向 {drho:4.2f} px/列,'
              f'方位 {2*np.pi*rho_rows[i]/C.PANO_W:4.2f} px/欄')

    i_top = int(np.argmin(np.abs(np.rad2deg(el_rows) - np.rad2deg(C.EL_TOP))))
    i_c30 = C.COMPASS_ROWS - 1
    span = abs(rho_rows[i_c30] - rho_rows[i_top])
    print(f'⚠ 羅盤帶(前 {C.COMPASS_ROWS} 列)徑向只佔 {span:.1f} px'
          f'({span/C.COMPASS_ROWS:.2f} px/列)——240px 裁切下上緣列嚴重過取樣;'
          f'實機建議裁切 ≥480px 或縮小 EL_TOP。')

    print('\n=== 閉環驗證(合成球照 → LUT 攤平 → 對解析全景,雙線性) ===')
    world = World()
    gt_cam = PanoCamera(cam_h=cam_h_eff, pix_noise=0.0, blur_exposure=0.0, quantize=False)
    pose = (1.5, 1.0, 0.3)
    ball1 = synth_ball_image(world, *pose, u_tab, eps_tab, cam_h_eff)
    est1 = unwarp_bilinear(ball1, lut_x, lut_y)
    gt1, _ = gt_cam.render(world, *pose, 0.0, np.random.default_rng(0))
    dth, conf, _ = ridf(norm(est1), norm(gt1))
    D = img_diff(norm(est1), norm(gt1))
    ok1 = abs(np.rad2deg(dth)) < 1.5
    print(f'同位姿:RIDF = {np.rad2deg(dth):+.2f}°(應≈0)conf={conf:.2f} IDF={D:.4f} '
          f'{"PASS" if ok1 else "FAIL"}')
    ball2 = synth_ball_image(world, pose[0], pose[1], pose[2] + np.deg2rad(30),
                             u_tab, eps_tab, cam_h_eff)
    est2 = unwarp_bilinear(ball2, lut_x, lut_y)
    dth2, _, _ = ridf(norm(est2), norm(est1))
    ok2 = abs(np.rad2deg(dth2) - 30) < 1.5
    print(f'+30° 手性/符號:RIDF = {np.rad2deg(dth2):+.2f}°(應≈+30)'
          f'{"PASS" if ok2 else "FAIL"}')

    np.save('pano_lut.npy', np.stack([lut_x, lut_y]).astype(np.float32))
    export_c(lut_x, lut_y)
    fig, axs = plt.subplots(1, 3, figsize=(12, 3.6), dpi=110)
    axs[0].imshow(ball1, cmap='gray', vmin=0, vmax=1)
    th_c = np.linspace(0, 2*np.pi, 200)
    for e_deg, cc in ((55, 'r'), (0, 'c'), (-5, 'y')):
        i = int(np.argmin(np.abs(np.rad2deg(el_rows) - e_deg)))
        axs[0].plot(CX + rho_rows[i]*np.cos(th_c), CY - rho_rows[i]*np.sin(th_c),
                    cc, lw=0.7, label=f'elev {e_deg} deg')
    axs[0].legend(fontsize=6); axs[0].set_title('synthetic ball image (OV2640 sim)')
    axs[1].imshow(est1, cmap='gray', vmin=0, vmax=1, aspect='auto')
    axs[1].set_title('LUT-unwarped 64x48')
    axs[2].imshow(gt1, cmap='gray', vmin=0, vmax=1, aspect='auto')
    axs[2].set_title('analytic panorama (ground truth)')
    for a in axs: a.set_xticks([]); a.set_yticks([])
    fig.tight_layout(); fig.savefig('mirror_calib.png')
    print('\n輸出:pano_lut.npy / pano_lut.h / mirror_calib.png')
